// <auto-generated />
using System;
using Integration.DatabaseAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Integration.DatabaseAccess.Migrations
{
    [DbContext(typeof(NibssNpsDbContext))]
    partial class NibssNpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Core")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Integration.Models.DatabaseAuditLog", b =>
                {
                    b.Property<string>("DatabaseAuditLogId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Succeded")
                        .HasColumnType("boolean");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.HasKey("DatabaseAuditLogId");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_DatabaseAuditLogs_StartTime");

                    b.HasIndex("TableName", "RecordId")
                        .HasDatabaseName("IX_DatabaseAuditLogs_TableName_RecordId");

                    b.ToTable("DatabaseAuditLogs", "Core");
                });

            modelBuilder.Entity("Integration.Models.Nps.BulkTransferItemLog", b =>
                {
                    b.Property<string>("BulkTransferItemLogId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<string>("AccountDesignation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AccountTier")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BulkTransferLogId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("CreditorAccountName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("CreditorAccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CreditorBankCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CreditorName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("IdType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IdValue")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("InstructionId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemSequence")
                        .HasColumnType("integer");

                    b.Property<string>("NameEnquiryMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Narration")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("StatusId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StatusReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("StatusReasonInformation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransactionStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("WebhookCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WebhookReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WebhookResponse")
                        .HasColumnType("text");

                    b.HasKey("BulkTransferItemLogId");

                    b.HasIndex("EndToEndId")
                        .IsUnique()
                        .HasDatabaseName("UX_BulkTransferItemLogs_EndToEndId");

                    b.HasIndex("SoftDeleted");

                    b.HasIndex("BulkTransferLogId", "ItemSequence")
                        .IsUnique()
                        .HasDatabaseName("UX_BulkTransferItemLogs_BulkTransferLogId_ItemSequence");

                    b.HasIndex("CreditorBankCode", "CreditorAccountNumber")
                        .HasDatabaseName("IX_BulkTransferItemLogs_CreditorBankCode_CreditorAccountNumber");

                    b.HasIndex("Status", "DateCreated")
                        .HasDatabaseName("IX_BulkTransferItemLogs_Status_DateCreated");

                    b.ToTable("BulkTransferItemLogs", "Core");
                });

            modelBuilder.Entity("Integration.Models.Nps.BulkTransferLog", b =>
                {
                    b.Property<string>("BulkTransferLogId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<bool>("AcknowledgedBySwitch")
                        .HasColumnType("boolean");

                    b.Property<bool>("BatchBooking")
                        .HasColumnType("boolean");

                    b.Property<string>("ChannelCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ChargeBearer")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("ControlSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DebtorAccountName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("DebtorAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DebtorBankCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("DebtorName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FailedTransactionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("FixedCollectionAmount")
                        .HasColumnType("boolean");

                    b.Property<string>("ForwardingAgentBic")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("GroupStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InitiatingPartyName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MandateCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int?>("NibbsHttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NibbsRespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NibbsResponse")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfTransactions")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentInformationId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int>("PendingTransactionCount")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestCreationDateTime")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestSentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestUniqueId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestedExecutionDate")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("ResponseMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<decimal>("SuccessfulAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SuccessfulTransactionCount")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WebhookCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WebhookReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WebhookResponse")
                        .HasColumnType("text");

                    b.HasKey("BulkTransferLogId");

                    b.HasIndex("SoftDeleted");

                    b.HasIndex("DebtorAccountNumber", "DateCreated")
                        .HasDatabaseName("IX_BulkTransferLogs_DebtorAccountNumber_DateCreated");

                    b.HasIndex("Direction", "PaymentInformationId")
                        .IsUnique()
                        .HasDatabaseName("UX_BulkTransferLogs_Direction_PaymentInformationId");

                    b.HasIndex("Direction", "RequestUniqueId")
                        .IsUnique()
                        .HasDatabaseName("UX_BulkTransferLogs_Direction_RequestUniqueId");

                    b.HasIndex("Status", "DateCreated")
                        .HasDatabaseName("IX_BulkTransferLogs_Status_DateCreated");

                    b.ToTable("BulkTransferLogs", "Core");
                });

            modelBuilder.Entity("Integration.Models.Nps.NameEnquiryLog", b =>
                {
                    b.Property<string>("NameEnquiryLogId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<string>("AccountDesignation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountTier")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("AcknowledgedBySwitch")
                        .HasColumnType("boolean");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IdType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IdValue")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("NibbsHttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NibbsRespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NibbsResponse")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestCreationDateTime")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestSentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestUniqueId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestedPartyName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("RequestingBankCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("RequestingPartyName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("ResolvedAccountName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("ResponseMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RiskRating")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("VerificationId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean");

                    b.Property<int>("WebhookCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WebhookReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WebhookResponse")
                        .HasColumnType("text");

                    b.HasKey("NameEnquiryLogId");

                    b.HasIndex("SoftDeleted");

                    b.HasIndex("VerificationId")
                        .HasDatabaseName("IX_NameEnquiryLogs_VerificationId");

                    b.HasIndex("BankCode", "AccountNumber")
                        .HasDatabaseName("IX_NameEnquiryLogs_BankCode_AccountNumber");

                    b.HasIndex("Direction", "RequestUniqueId")
                        .HasDatabaseName("IX_NameEnquiryLogs_Direction_RequestUniqueId");

                    b.HasIndex("Status", "DateCreated")
                        .HasDatabaseName("IX_NameEnquiryLogs_Status_DateCreated");

                    b.HasIndex("Direction", "RequestUniqueId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_NameEnquiryLogs_Direction_RequestUniqueId_AccountNumber");

                    b.ToTable("NameEnquiryLogs", "Core");
                });

            modelBuilder.Entity("Integration.Models.Nps.SingleTransferLog", b =>
                {
                    b.Property<string>("SingleTransferLogId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .UseCollation("C");

                    b.Property<bool>("AcknowledgedBySwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ChannelCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("CreditorAccountName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("CreditorAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CreditorBankCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CreditorName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DebtorAccountName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("DebtorAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DebtorBankCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("DebtorName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("EndToEndId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GroupStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InstructionId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatusQueryAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastStatusQueryMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("NameEnquiryMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Narration")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int?>("NibbsHttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NibbsRespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NibbsResponse")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestCreationDateTime")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestSentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestUniqueId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("ResponseMessageId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("RiskRating")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SettlementDate")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("StatusId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("StatusQueryCount")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("StatusReasonInformation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("TransactionLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("WebhookCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WebhookReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WebhookResponse")
                        .HasColumnType("text");

                    b.HasKey("SingleTransferLogId");

                    b.HasIndex("EndToEndId")
                        .HasDatabaseName("IX_SingleTransferLogs_EndToEndId");

                    b.HasIndex("InstructionId")
                        .HasDatabaseName("IX_SingleTransferLogs_InstructionId");

                    b.HasIndex("NameEnquiryMessageId")
                        .HasDatabaseName("IX_SingleTransferLogs_NameEnquiryMessageId");

                    b.HasIndex("SoftDeleted");

                    b.HasIndex("DebtorAccountNumber", "DateCreated")
                        .HasDatabaseName("IX_SingleTransferLogs_DebtorAccountNumber_DateCreated");

                    b.HasIndex("Direction", "RequestUniqueId")
                        .IsUnique()
                        .HasDatabaseName("UX_SingleTransferLogs_Direction_RequestUniqueId");

                    b.HasIndex("Direction", "TransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SingleTransferLogs_Direction_TransactionId");

                    b.HasIndex("Status", "DateCreated")
                        .HasDatabaseName("IX_SingleTransferLogs_Status_DateCreated");

                    b.ToTable("SingleTransferLogs", "Core");
                });

            modelBuilder.Entity("Integration.Models.Nps.BulkTransferItemLog", b =>
                {
                    b.HasOne("Integration.Models.Nps.BulkTransferLog", "BulkTransfer")
                        .WithMany("Items")
                        .HasForeignKey("BulkTransferLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BulkTransfer");
                });

            modelBuilder.Entity("Integration.Models.Nps.BulkTransferLog", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
